### ISSUE TITLE
As a user, I want to see visual representations of data entered in current and previous assessments

### ISSUE THREAD

**Issue by sergioespana** [nielsrowinbik/open-sea#8]
Initially, the tool is stateless. Then it will be able to store one audit per organisation (user). Then it will allow to define auditing periods (e.g. year) and will store the information of each period. This will enable visualisation mechanisms #5 that show historic data and trends (e.g. line charts).

**Comment by nielsrowinbik** [comment]
Visualisation possible as of 6b14a3a0a1c9337b1ab923fcb15744275062756c. Functionality will be extended by #26.
